wandb_version: 1

spectral_transform:
  desc: null
  value: sht
img_size:
  desc: null
  value:
  - 256
  - 512
grid:
  desc: null
  value: equiangular
num_layers:
  desc: null
  value: 4
scale_factor:
  desc: null
  value: 3
embed_dim:
  desc: null
  value: 16
operator_type:
  desc: null
  value: driscoll-healy
big_skip:
  desc: null
  value: false
pos_embed:
  desc: null
  value: false
use_mlp:
  desc: null
  value: false
normalization_layer:
  desc: null
  value: none
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1733077270
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.6
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
